name: Deploy prod to Heroku
on:
  push:
    branches:
      - features/test
  pull_request:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: linter
        uses: michaelw90/PHP-lint@master
      - name: Security checker
        uses: symfonycorp/security-checker-action@v2
      - name: PHPstan
        uses: docker://oskarstark/phpstan-ga
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://iim-a4-projet-laravel-preprod.herokuapp.com/
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
     # - name: Create Sentry release
        #uses: getsentry/action-release@v1
       # env:
        #  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        #  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        #  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
       # with:
        #  environment: production
      - name: Deploy heroku
        uses: akhileshns/heroku-deploy@v3.5.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY_DEV}}
          heroku_app_name: ${{secrets.HEROKU_APP_DEV}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL_DEV}}
